#!/usr/bin/env node
// Merge forge build artifacts into the committed ABI files under packages/contracts/abi/.
//
// The Diamond (EIP-2535) presents one address whose ABI is the union of every facet's
// ABI, so TaskMarket.json is that union, de-duplicated and order-stable. The reward
// hook contracts are deployed separately, so each gets its own file.
//
// Each ABI is written twice, from the same forge artifact in the same pass:
//
//   - abi/<Name>.json           -- the artifact itself, language-neutral.
//   - abi/generated/<Name>.ts   -- the same entries as a TypeScript `as const` literal.
//
// The .ts file is what TypeScript consumers import. A JSON import widens every string to
// `string`, so nothing about an event's name or shape survives into the type system; an
// `as const` literal keeps all of it, which is what lets the backend check its event
// names against the contracts at compile time rather than at runtime (ADR-0065). No code
// generation dependency is involved -- `as const` is the whole mechanism, and viem's
// types (built on abitype) infer from it directly.
//
// These files are the single source of truth the backend indexer reads its event
// definitions from (apps/backend/src/services/indexer-abi-events.ts). `make contract
// abi-check` regenerates them and fails if the committed copies differ, mirroring the
// `forge snapshot --check` gas gate -- a stale committed ABI would silently defeat the
// indexer's drift guard. Both files come out of this one script and the check covers the
// whole abi/ directory, so the artifact and the types it feeds cannot disagree.
//
// Run from packages/contracts (`pnpm generate-abi`, or via `make build contracts`).

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIAMOND_FACETS = [
  'DiamondCutFacet.sol/DiamondCutFacet.json',
  'DiamondLoupeFacet.sol/DiamondLoupeFacet.json',
  'AdminFacet.sol/AdminFacet.json',
  'CoreFacet.sol/CoreFacet.json',
  'AuctionFacet.sol/AuctionFacet.json',
  'AcceptanceFacet.sol/AcceptanceFacet.json',
  'EvaluatorFacet.sol/EvaluatorFacet.json',
  'RatingFacet.sol/RatingFacet.json',
  'RegistryFacet.sol/RegistryFacet.json',
];

// Standalone contracts deployed at their own addresses. The indexer polls each of
// these separately, so each needs its own ABI file.
//
// The forwarder is here for a different reason than the rest: nothing indexes it, but every
// relayed call passes through it, so its errors are the ones a relayed write is most likely to
// revert with. The backend derives its error map from these artifacts, and while the forwarder
// was absent that map could not name a single one of them -- an unnamed revert is treated as
// transient and retried against a call that can only revert again.
const STANDALONE: Record<string, string> = {
  TaskTokenRewardHook: 'TaskTokenRewardHook.sol/TaskTokenRewardHook.json',
  RewardVault: 'RewardVault.sol/RewardVault.json',
  EpochBudget: 'EpochBudget.sol/EpochBudget.json',
  TaskMarketForwarder: 'TaskMarketForwarder.sol/TaskMarketForwarder.json',
};

type AbiEntry = Record<string, unknown>;

function loadAbi(artifact: string): AbiEntry[] {
  const path = join('out', artifact);
  if (!existsSync(path)) {
    console.error(`Missing forge artifact: ${path} (run \`forge build --root packages/contracts\` first)`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(path, 'utf8')).abi as AbiEntry[];
}

/**
 * Serialise with every object's keys in sorted order, at every depth. Used only as a
 * dedupe key: two facets declaring the same function or error must collapse to one
 * entry even if their artifacts happen to order the keys differently. The emitted
 * files keep the artifact's own key order -- this is not what gets written.
 */
function stableKey(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map(stableKey).join(',')}]`;
  }
  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
      .map(([key, nested]) => `${JSON.stringify(key)}:${stableKey(nested)}`);
    return `{${entries.join(',')}}`;
  }
  return JSON.stringify(value);
}

const TS_HEADER = `\
// Generated by \`make build contracts\` (packages/contracts/scripts/generate-abi.ts).
// Do not edit by hand -- \`make contract abi-check\` fails if this file differs from
// what the contract sources produce.
//
// \`as const\` is load-bearing: it is what preserves every event name, parameter name
// and parameter type as a literal type, so TypeScript consumers get compile-time
// checking against the contracts (ADR-0065). The .json file beside this one carries
// the same entries for non-TypeScript tooling.
`;

function write(name: string, entries: AbiEntry[]): void {
  const body = JSON.stringify(entries, null, 2);

  writeFileSync(join('abi', `${name}.json`), `${body}\n`);

  mkdirSync(join('abi', 'generated'), { recursive: true });
  writeFileSync(
    join('abi', 'generated', `${name}.ts`),
    `${TS_HEADER}export const ${name}ABI = ${body} as const;\n`
  );

  console.log(`ABI: ${entries.length} entries -> abi/${name}.json, abi/generated/${name}.ts`);
}

function main(): void {
  const merged: AbiEntry[] = [];
  const seen = new Set<string>();
  for (const artifact of DIAMOND_FACETS) {
    for (const entry of loadAbi(artifact)) {
      const key = stableKey(entry);
      if (seen.has(key)) continue;
      seen.add(key);
      merged.push(entry);
    }
  }
  write('TaskMarket', merged);

  for (const [name, artifact] of Object.entries(STANDALONE)) {
    write(name, loadAbi(artifact));
  }
}

main();
